---
- hosts: k8s-master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Remove phpMyAdmin with Helm.
      community.kubernetes.helm:
        name: phpmyadmin
        chart_ref: bitnami/phpmyadmin
        release_namespace: default
        state: absent

    - name: Delete helm binary.
      file:
        path: /usr/local/bin/helm
        state: absent
