---
- hosts: k8s-master
  become: yes
  tasks:
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Add Bitnami's chart repository.
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

- hosts: k8s-master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure K8s module dependencies are installed.
      package:
        name: python3-pip
        state: present"
    - name: Ensure K8s module dependencies are installed.
      pip:
        name: pyyaml
        state: present
    - name: Install phpMyAdmin with Helm.
      kubernetes.core.helm:
        name: phpmyadmin
        chart_ref: bitnami/phpmyadmin
        release_namespace: default
        values:
          service:
            type: NodePort

- hosts: k8s-master
  become: yes
  tasks:
    - name: Ensure K8s module dependencies are installed.
      pip:
        name: openshift
        state: present

    - name: Get the details of the phpmyadmin Service.
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        name: phpmyadmin
        namespace: default
      register: phpmyadmin_service

    - name: Print the NodePort of the phpmyadmin Service.
      debug:
        var: phpmyadmin_service.result.spec.ports[0].nodePort
